import type { Metadata } from 'next'; import Link from 'next/link'; import { notFound } from 'next/navigation'; import { JsonLd } from '@/components/JsonLd'; import { policies } from '@/data/policies'; import { getPublicPolicyById } from '@/lib/policy-store'; import { siteConfig } from '@/lib/site';
export function generateStaticParams() { return policies.map((policy) => ({ id: policy.id })); }
export async function generateMetadata({ params }: { params: { id: string } }): Promise<Metadata> { const policy = await getPublicPolicyById(params.id); return policy ? { title: `${policy.title} 신청 대상과 방법`, description: policy.summary, keywords: policy.keywords, alternates: { canonical: `/policies/${policy.id}` } } : {}; }
export default async function PolicyDetailPage({ params }: { params: { id: string } }) {
  const policy = await getPublicPolicyById(params.id); if (!policy) notFound();
  const jsonLd = { '@context': 'https://schema.org', '@type': 'GovernmentService', name: policy.title, description: policy.summary, url: `${siteConfig.url}/policies/${policy.id}`, provider: { '@type': 'GovernmentOrganization', name: policy.ministry || policy.sourceName || '대한민국 공공기관' } };
  const info = [{ label: '담당 부처', value: policy.ministry }, { label: '담당 부서', value: policy.department }, { label: '문의처', value: policy.contact }, { label: '지원 주기', value: policy.supportCycle }, { label: '제공 방식', value: policy.provisionType }, { label: '온라인 신청', value: policy.onlineApplyAvailable === null ? null : policy.onlineApplyAvailable ? '가능' : '불가' }].filter((item) => item.value);
  return <main className="mx-auto max-w-4xl px-4 py-10"><JsonLd data={jsonLd} /><Link href="/policies" className="text-sm font-bold text-brand">← 정책 목록</Link><article className="mt-5 rounded-[2rem] bg-white p-6 shadow-sm md:p-10"><div className="flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-blue-50 px-3 py-1 text-brand">{policy.category}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-slate-600">{policy.region}</span>{policy.lifeCycles.map((item) => <span key={item} className="rounded-full bg-emerald-50 px-3 py-1 text-emerald-700">{item}</span>)}</div><h1 className="mt-5 text-4xl font-black tracking-tight">{policy.title}</h1><p className="mt-4 text-lg leading-8 text-slate-600">{policy.summary}</p><div className="ad-box my-8">광고 영역</div>
    <section className="grid gap-4 md:grid-cols-2"><div className="rounded-3xl bg-soft p-5"><p className="text-sm text-slate-500">지원 내용</p><p className="mt-1 text-xl font-black">{policy.amount}</p></div><div className="rounded-3xl bg-soft p-5"><p className="text-sm text-slate-500">신청·지원 기간</p><p className="mt-1 text-xl font-black">{policy.deadline}</p></div></section>
    {info.length > 0 && <section className="mt-8"><h2 className="text-2xl font-black">기관 및 신청 정보</h2><dl className="mt-4 grid gap-3 sm:grid-cols-2">{info.map((item) => <div key={item.label} className="rounded-2xl border border-line p-4"><dt className="text-sm text-slate-500">{item.label}</dt><dd className="mt-1 font-bold">{String(item.value)}</dd></div>)}</dl></section>}
    {policy.themes.length > 0 && <section className="mt-8"><h2 className="text-2xl font-black">관심 주제</h2><div className="mt-4 flex flex-wrap gap-2">{policy.themes.map((item) => <span key={item} className="rounded-full bg-sky-50 px-3 py-2 text-sm font-bold text-brand">{item}</span>)}</div></section>}
    <section className="mt-8"><h2 className="text-2xl font-black">지원 대상</h2><ul className="mt-4 space-y-2 text-slate-700">{policy.target.length ? policy.target.map((item) => <li key={item}>• {item}</li>) : <li>공식 상세정보에서 대상 조건을 확인하세요.</li>}</ul></section>
    <section className="mt-8"><h2 className="text-2xl font-black">신청 방법</h2><p className="mt-4 leading-8 text-slate-700">공식 상세 페이지에서 최신 대상 조건과 신청 절차를 확인한 뒤 접수하세요.</p><a href={policy.applyUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex rounded-2xl bg-brand px-6 py-4 font-bold text-white">복지로 공식 상세정보 확인</a></section>
    <aside className="mt-8 rounded-2xl bg-amber-50 p-5 text-sm leading-6 text-amber-900">정책 정보는 변경될 수 있습니다. 실제 신청 전 담당 기관과 공식 페이지에서 최신 내용을 확인하세요.</aside>
  </article></main>;
}
