'use client';
import { FormEvent, useEffect, useState } from 'react';
type Answer = { id: string; nickname: string; content: string; createdAt: string };
type Question = { id: string; nickname: string; title: string; content: string; category: string; createdAt: string; answers: Answer[] };
export function QnaBoard() {
  const [questions, setQuestions] = useState<Question[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [openId, setOpenId] = useState<string | null>(null);
  const load = async () => { const response = await fetch('/api/qna', { cache: 'no-store' }); const data = await response.json(); setQuestions(data.questions || []); setLoading(false); };
  useEffect(() => { load().catch(() => { setMessage('질문 목록을 불러오지 못했습니다.'); setLoading(false); }); }, []);
  async function submitQuestion(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const body = Object.fromEntries(new FormData(form)); setMessage('등록 중...');
    const response = await fetch('/api/qna', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json();
    if (!response.ok) return setMessage(data.message || '등록하지 못했습니다.'); form.reset(); setMessage('질문이 등록되었습니다.'); await load();
  }
  async function submitAnswer(event: FormEvent<HTMLFormElement>, id: string) {
    event.preventDefault(); const form = event.currentTarget; const body = Object.fromEntries(new FormData(form)); setMessage('답변 등록 중...');
    const response = await fetch(`/api/qna/${id}/answers`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json();
    if (!response.ok) return setMessage(data.message || '답변을 등록하지 못했습니다.'); form.reset(); setMessage('답변이 등록되었습니다.'); await load();
  }
  return <div className="grid gap-6 lg:grid-cols-[380px_1fr]">
    <form onSubmit={submitQuestion} className="h-fit rounded-3xl border border-line bg-white p-6 shadow-sm"><h2 className="text-xl font-black">질문하기</h2><p className="mt-2 text-sm text-slate-500">개인정보는 입력하지 말고, 공식 신청 여부는 해당 기관에서 확인하세요.</p><div className="mt-5 space-y-3"><input name="website" tabIndex={-1} autoComplete="off" className="hidden" /><input name="nickname" maxLength={20} required placeholder="닉네임" className="w-full rounded-xl border border-line px-4 py-3" /><select name="category" className="w-full rounded-xl border border-line px-4 py-3"><option>정책문의</option><option>신청방법</option><option>자격조건</option><option>경험공유</option></select><input name="title" maxLength={80} required placeholder="질문 제목" className="w-full rounded-xl border border-line px-4 py-3" /><textarea name="content" maxLength={1500} required rows={7} placeholder="궁금한 내용을 자세히 적어주세요." className="w-full resize-none rounded-xl border border-line px-4 py-3" /><button className="w-full rounded-xl bg-brand px-5 py-3 font-bold text-white">질문 등록</button></div></form>
    <section><div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-black">최근 질문</h2><span className="text-sm font-bold text-slate-400">{questions.length}건</span></div>{message && <p className="mb-3 rounded-xl bg-sky-50 px-4 py-3 text-sm font-bold text-brand">{message}</p>}{loading && <p className="rounded-2xl bg-white p-8 text-center text-slate-400">불러오는 중...</p>}<div className="space-y-3">{questions.map((question) => <article key={question.id} className="rounded-2xl border border-line bg-white p-5 shadow-sm"><button type="button" onClick={() => setOpenId(openId === question.id ? null : question.id)} className="w-full text-left"><div className="flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full bg-sky-50 px-2.5 py-1 font-bold text-brand">{question.category}</span><span className="text-slate-400">{question.nickname} · {new Date(question.createdAt).toLocaleDateString('ko-KR')}</span><span className="ml-auto font-bold text-brand">답변 {question.answers.length}</span></div><h3 className="mt-3 text-lg font-black">{question.title}</h3><p className="mt-2 line-clamp-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{question.content}</p></button>{openId === question.id && <div className="mt-5 border-t border-line pt-5"><p className="whitespace-pre-wrap leading-7 text-slate-700">{question.content}</p><div className="mt-5 space-y-3">{question.answers.map((answer) => <div key={answer.id} className="rounded-xl bg-soft p-4"><p className="text-xs font-bold text-brand">{answer.nickname} · {new Date(answer.createdAt).toLocaleString('ko-KR')}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{answer.content}</p></div>)}</div><form onSubmit={(event) => submitAnswer(event, question.id)} className="mt-4 grid gap-2 sm:grid-cols-[140px_1fr_auto]"><input name="website" tabIndex={-1} className="hidden" /><input name="nickname" maxLength={20} required placeholder="닉네임" className="rounded-xl border border-line px-3 py-2.5" /><input name="content" maxLength={1000} required placeholder="답변을 입력하세요" className="rounded-xl border border-line px-3 py-2.5" /><button className="rounded-xl bg-ink px-5 py-2.5 font-bold text-white">답변</button></form></div>}</article>)}{!loading && !questions.length && <p className="rounded-2xl bg-white p-10 text-center text-slate-400">첫 질문을 남겨보세요.</p>}</div></section>
  </div>;
}
